import * as stylex from '@stylexjs/stylex'
import { tokens } from '../../styles/tokens.stylex'
import { size, text, weight } from '../../styles/scale.stylex'

export const commandStyles = stylex.create({
  popup: {
    padding: 0,
    backgroundColor: tokens['--xid-surface'],
    color: tokens['--xid-fg'],
    fontFamily: tokens['--xid-font'],
    boxShadow: `0 0 0 1px ${tokens['--xid-border']}, ${tokens['--xid-shadow-lg']}`,
    overflow: 'hidden',
  },
  inputRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.625rem',
    height: '3.25rem',
    paddingInline: '1rem',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens['--xid-border'],
  },
  inputIcon: {
    display: 'inline-flex',
    color: tokens['--xid-muted-foreground'],
  },
  input: {
    flexGrow: 1,
    minWidth: 0,
    height: '100%',
    padding: 0,
    borderWidth: 0,
    outline: 'none',
    backgroundColor: 'transparent',
    color: tokens['--xid-fg'],
    fontFamily: 'inherit',
    fontSize: text.md,
    '::placeholder': {
      color: tokens['--xid-faint-foreground'],
    },
  },
  escape: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    width: { default: '1.75rem', '@media (pointer: coarse)': size.touch },
    height: { default: '1.75rem', '@media (pointer: coarse)': size.touch },
    padding: 0,
    borderWidth: 0,
    borderRadius: tokens['--xid-radius-sm'],
    backgroundColor: { default: 'transparent', ':hover': tokens['--xid-muted'] },
    color: tokens['--xid-muted-foreground'],
    cursor: 'pointer',
  },
  list: {
    flexGrow: 1,
    maxHeight: { default: '22rem', '@media (max-width: 47.99rem)': 'none' },
    overflowY: 'auto',
    padding: '0.375rem',
  },
  // Empty 作为常驻 live region 一直挂载,有结果时内容为空,不能留出内边距。
  empty: {
    paddingBlock: { default: '1.5rem', ':empty': 0 },
    paddingInline: { default: '0.625rem', ':empty': 0 },
    color: tokens['--xid-muted-foreground'],
    fontSize: text.sm,
  },
  groupLabel: {
    display: 'flex',
    alignItems: 'center',
    height: '1.75rem',
    paddingInline: '0.625rem',
    color: tokens['--xid-faint-foreground'],
    fontSize: text.xs,
    fontWeight: weight.medium,
    letterSpacing: tokens['--xid-tracking-small'],
  },
  item: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    minHeight: { default: '2.25rem', '@media (pointer: coarse)': size.touch },
    paddingBlock: '0.375rem',
    paddingInline: '0.625rem',
    borderRadius: tokens['--xid-radius'],
    cursor: 'default',
    outline: 'none',
  },
  itemHighlighted: {
    backgroundColor: tokens['--xid-muted'],
  },
  itemText: {
    display: 'flex',
    flexDirection: 'column',
    flexGrow: 1,
    minWidth: 0,
  },
  itemLabel: {
    fontSize: text.base,
    lineHeight: '1.125rem',
    color: tokens['--xid-fg'],
  },
  itemDescription: {
    fontSize: text.sm,
    lineHeight: '1rem',
    color: tokens['--xid-muted-foreground'],
  },
  footer: {
    display: { default: 'flex', '@media (pointer: coarse)': 'none' },
    alignItems: 'center',
    gap: '1rem',
    height: '2.25rem',
    paddingInline: '1rem',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens['--xid-border'],
    color: tokens['--xid-muted-foreground'],
    fontSize: text.xs,
  },
})
