import * as stylex from '@stylexjs/stylex'
import { tokens } from '@xid-kit/web-ui/styles/tokens.stylex'

export const controlPlaneStyles = stylex.create({
  root: {
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
    paddingBottom: 'clamp(2rem, 3vw, 4rem)',
  },
  header: {
    paddingInline: 'clamp(1rem, 2.5vw, 4rem)',
    paddingTop: 'clamp(1.75rem, 2vw, 3rem)',
    paddingBottom: 'clamp(1.25rem, 1.5vw, 2rem)',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens['--xid-border'],
  },
  title: {
    margin: 0,
    fontSize: 'clamp(1.75rem, 1.05rem + 1.5vw, 2.75rem)',
    fontWeight: 620,
    lineHeight: 1.05,
    letterSpacing: '-0.03em',
    color: tokens['--xid-fg'],
    textWrap: 'balance',
  },
  lead: {
    maxWidth: '48rem',
    margin: '0.5rem 0 0',
    color: tokens['--xid-muted-foreground'],
    fontFamily: tokens['--xid-font'],
    fontSize: '0.875rem',
    lineHeight: 1.6,
  },
  message: {
    paddingInline: 'clamp(1rem, 2.5vw, 4rem)',
    paddingBlock: '1.5rem',
  },
  toolbar: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'flex-end',
    gap: '0.75rem',
    paddingInline: 'clamp(1rem, 2.5vw, 4rem)',
    paddingBlock: 'clamp(1.25rem, 1.6vw, 2rem)',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens['--xid-border'],
  },
  toolbarField: {
    flex: '1 1 18rem',
    maxWidth: '36rem',
    minWidth: 0,
  },
  section: {
    paddingInline: 'clamp(1rem, 2.5vw, 4rem)',
    paddingBlock: 'clamp(1.5rem, 1.6vw, 2.5rem)',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens['--xid-border'],
  },
  sectionStack: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  sectionHeadingRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: '0.5rem 1rem',
  },
  sectionDescription: {
    margin: 0,
    maxWidth: '48rem',
    color: tokens['--xid-muted-foreground'],
    fontFamily: tokens['--xid-font'],
    fontSize: '0.8125rem',
    lineHeight: 1.55,
  },
  createSection: {
    display: 'grid',
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 64rem)': 'minmax(0, 5fr) minmax(0, 7fr)',
    },
    gap: {
      default: '1.25rem',
      '@media (min-width: 64rem)': 0,
    },
    paddingInline: 'clamp(1rem, 2.5vw, 4rem)',
    paddingBlock: 'clamp(1.5rem, 1.6vw, 2.5rem)',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens['--xid-border'],
  },
  sectionMeta: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.375rem',
    paddingInlineEnd: {
      default: 0,
      '@media (min-width: 64rem)': 'clamp(1.75rem, 2vw, 3.5rem)',
    },
  },
  controls: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    maxWidth: '48rem',
    paddingInlineStart: {
      default: 0,
      '@media (min-width: 64rem)': 'clamp(1.75rem, 2vw, 3.5rem)',
    },
    borderInlineStartWidth: {
      default: 0,
      '@media (min-width: 64rem)': '1px',
    },
    borderInlineStartStyle: 'solid',
    borderInlineStartColor: tokens['--xid-border'],
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 42rem)': 'repeat(2, minmax(0, 1fr))',
    },
    gap: '0.875rem',
  },
  formWide: {
    gridColumn: {
      default: 'auto',
      '@media (min-width: 42rem)': '1 / -1',
    },
  },
  formActions: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '0.75rem',
  },
  select: {
    width: '100%',
    minHeight: '2.5rem',
    paddingBlock: 0,
    paddingInline: '0.75rem',
    borderRadius: tokens['--xid-radius'],
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens['--xid-border'],
    backgroundColor: tokens['--xid-bg'],
    color: tokens['--xid-fg'],
    fontFamily: tokens['--xid-font'],
    fontSize: '0.875rem',
  },
  textarea: {
    width: '100%',
    minHeight: '7rem',
    resize: 'vertical',
    boxSizing: 'border-box',
    padding: '0.75rem',
    borderRadius: tokens['--xid-radius'],
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens['--xid-border'],
    backgroundColor: tokens['--xid-bg'],
    color: tokens['--xid-fg'],
    fontFamily: tokens['--xid-font-mono'],
    fontSize: '0.8125rem',
    lineHeight: 1.5,
  },
  textareaInvalid: {
    borderColor: tokens['--xid-danger'],
  },
  actionGroup: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.375rem',
  },
  actionButton: {
    minHeight: '1.75rem',
    paddingBlock: 0,
    paddingInline: '0.625rem',
    fontSize: '0.75rem',
  },
  mono: {
    fontFamily: tokens['--xid-font-mono'],
    fontSize: '0.8125rem',
    wordBreak: 'break-all',
  },
  muted: {
    color: tokens['--xid-muted-foreground'],
    fontSize: '0.8125rem',
  },
  selectorSummary: {
    margin: 0,
    color: tokens['--xid-muted-foreground'],
    fontFamily: tokens['--xid-font-mono'],
    fontSize: '0.75rem',
    letterSpacing: '0.04em',
  },
  split: {
    display: 'grid',
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 76rem)': 'repeat(2, minmax(0, 1fr))',
    },
    gap: 'clamp(1.5rem, 2vw, 3rem)',
  },
  splitColumn: {
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  dividerColumn: {
    paddingInlineStart: {
      default: 0,
      '@media (min-width: 76rem)': 'clamp(1.5rem, 2vw, 3rem)',
    },
    borderInlineStartWidth: {
      default: 0,
      '@media (min-width: 76rem)': '1px',
    },
    borderInlineStartStyle: 'solid',
    borderInlineStartColor: tokens['--xid-border'],
  },
  codeBlock: {
    display: 'block',
    maxWidth: '36rem',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    padding: '0.5rem',
    borderRadius: tokens['--xid-radius-sm'],
    backgroundColor: tokens['--xid-muted'],
    color: tokens['--xid-fg'],
    fontFamily: tokens['--xid-font-mono'],
    fontSize: '0.75rem',
    lineHeight: 1.5,
  },
})
