// 账户门户页面骨架:单列 640px 工作区,分节用细线与间距分组,不包卡片。
// 档位:<48rem 手机(16px 边距),48–64rem 平板(40px),≥64rem 桌面(64px)。

import * as stylex from '@stylexjs/stylex'
import { leading, text, weight } from '@xid-kit/web-ui/styles/scale.stylex'
import { tokens } from '../../styles/tokens.stylex'

export const surface = stylex.create({
  content: {
    display: 'flex',
    flexDirection: 'column',
    gap: { default: '2rem', '@media (min-width: 48rem)': '2.5rem' },
    width: '100%',
    paddingBlockStart: { default: '1.5rem', '@media (min-width: 48rem)': '2.5rem' },
    paddingBlockEnd: '4rem',
    paddingInline: {
      default: '1rem',
      '@media (min-width: 48rem)': '2.5rem',
      '@media (min-width: 64rem)': '4rem',
    },
    boxSizing: 'border-box',
    minWidth: 0,
  },
  column: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    maxWidth: '40rem',
    minWidth: 0,
  },
  pageHeader: {
    display: 'flex',
    flexDirection: { default: 'column', '@media (min-width: 48rem)': 'row' },
    alignItems: { default: 'stretch', '@media (min-width: 48rem)': 'flex-start' },
    justifyContent: 'space-between',
    gap: { default: '1rem', '@media (min-width: 48rem)': '1.5rem' },
  },
  pageHeaderLead: {
    display: 'flex',
    alignItems: 'center',
    gap: '1.25rem',
    minWidth: 0,
  },
  pageHeaderText: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
    minWidth: 0,
  },
  pageTitle: {
    margin: 0,
    fontSize: text.xl,
    lineHeight: leading.xl,
    fontWeight: weight.display,
    letterSpacing: tokens['--xid-tracking-heading'],
    color: tokens['--xid-fg'],
    textWrap: 'balance',
  },
  pageLead: {
    margin: 0,
    fontSize: text.base,
    lineHeight: '1.375rem',
    color: tokens['--xid-muted-foreground'],
    textWrap: 'pretty',
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
  },
  sectionHeader: {
    display: 'flex',
    flexDirection: { default: 'column', '@media (min-width: 30rem)': 'row' },
    alignItems: { default: 'stretch', '@media (min-width: 30rem)': 'flex-end' },
    justifyContent: 'space-between',
    gap: '0.75rem',
    paddingBlockEnd: '0.75rem',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens['--xid-border'],
  },
  sectionHeaderText: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
    minWidth: 0,
  },
  sectionTitleRow: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '0.625rem',
  },
  sectionTitle: {
    margin: 0,
    fontSize: text.lg,
    lineHeight: leading.lg,
    fontWeight: weight.display,
    letterSpacing: tokens['--xid-tracking-title'],
    color: tokens['--xid-fg'],
  },
  sectionDescription: {
    margin: 0,
    fontSize: text.sm,
    lineHeight: leading.sm,
    color: tokens['--xid-muted-foreground'],
    textWrap: 'pretty',
  },
  // 手机上主操作占满一行(grid 子项默认拉伸),宽屏回到行尾。
  sectionAction: {
    display: { default: 'grid', '@media (min-width: 30rem)': 'flex' },
    flexShrink: 0,
    gap: '0.5rem',
  },
  row: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '0.5rem 0.75rem',
    paddingBlock: '0.75rem',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens['--xid-border'],
    minWidth: 0,
  },
  rowMain: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.125rem',
    flexGrow: 1,
    flexBasis: '14rem',
    minWidth: 0,
  },
  rowTitleLine: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '0.5rem',
    minWidth: 0,
  },
  rowTitle: {
    fontSize: text.base,
    lineHeight: leading.base,
    fontWeight: weight.medium,
    color: tokens['--xid-fg'],
    overflowWrap: 'anywhere',
  },
  rowValue: {
    fontSize: text.base,
    lineHeight: leading.base,
    color: tokens['--xid-fg'],
    overflowWrap: 'anywhere',
  },
  rowMeta: {
    margin: 0,
    fontSize: text.sm,
    lineHeight: leading.sm,
    color: tokens['--xid-muted-foreground'],
    fontVariantNumeric: 'tabular-nums',
    overflowWrap: 'anywhere',
  },
  rowActions: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '0.25rem',
    marginInlineStart: 'auto',
  },
  keyRow: {
    display: 'flex',
    flexDirection: { default: 'column', '@media (min-width: 30rem)': 'row' },
    gap: '0.125rem 1rem',
    paddingBlock: '0.75rem',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens['--xid-border'],
  },
  keyLabel: {
    flexShrink: 0,
    width: { default: 'auto', '@media (min-width: 30rem)': '11.25rem' },
    fontSize: text.base,
    lineHeight: leading.base,
    color: tokens['--xid-muted-foreground'],
  },
  iconTile: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    width: '2rem',
    height: '2rem',
    borderRadius: tokens['--xid-radius'],
    backgroundColor: tokens['--xid-sidebar'],
    boxShadow: `inset 0 0 0 1px ${tokens['--xid-border']}`,
    color: tokens['--xid-muted-foreground'],
  },
  subheading: {
    margin: 0,
    paddingBlockStart: '1.25rem',
    paddingBlockEnd: '0.5rem',
    fontSize: text.sm,
    lineHeight: leading.sm,
    fontWeight: weight.medium,
    color: tokens['--xid-fg'],
  },
  note: {
    margin: 0,
    paddingBlockStart: '0.75rem',
    fontSize: text.sm,
    lineHeight: leading.sm,
    color: tokens['--xid-muted-foreground'],
  },
  quietButton: {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: { default: '2rem', '@media (pointer: coarse)': '2.75rem' },
    paddingInline: '0.625rem',
    borderWidth: 0,
    borderRadius: tokens['--xid-radius'],
    backgroundColor: { default: 'transparent', ':hover': tokens['--xid-muted'] },
    color: tokens['--xid-fg'],
    fontFamily: tokens['--xid-font'],
    fontSize: text.sm,
    lineHeight: leading.sm,
    fontWeight: weight.medium,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  dangerText: {
    color: tokens['--xid-danger'],
  },
  linkButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.25rem',
    padding: 0,
    borderWidth: 0,
    backgroundColor: 'transparent',
    color: tokens['--xid-accent'],
    fontFamily: tokens['--xid-font'],
    fontSize: text.sm,
    lineHeight: leading.sm,
    fontWeight: weight.medium,
    textDecoration: { default: 'none', ':hover': 'underline' },
    cursor: 'pointer',
  },
  formStack: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  inlineError: {
    margin: 0,
    fontSize: text.sm,
    lineHeight: leading.sm,
    color: tokens['--xid-danger'],
  },
  skeletonStack: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
    paddingBlock: '0.75rem',
  },
})
