// 详情页共用:头部(头像 + 标题 + 状态 + ID)、标签栏、≥90rem 左侧 sticky 关键属性栏、键值行与分节。

import * as stylex from '@stylexjs/stylex'
import { tokens } from '@xid-kit/web-ui/styles/tokens.stylex'
import { leading, text, weight } from '@xid-kit/web-ui/styles/scale.stylex'

export const detail = stylex.create({
  header: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '1rem',
  },
  identity: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    minWidth: 0,
    flex: '1 1 20rem',
  },
  avatar: {
    display: { default: 'none', '@media (min-width: 48rem)': 'inline-flex' },
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    width: '3rem',
    height: '3rem',
    borderRadius: tokens['--xid-radius-full'],
    backgroundColor: tokens['--xid-muted'],
    color: tokens['--xid-muted-foreground'],
    fontSize: text.base,
    fontWeight: weight.medium,
  },
  titleBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.375rem',
    minWidth: 0,
  },
  titleRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '0.5rem 0.75rem',
  },
  title: {
    margin: 0,
    fontSize: { default: text.lg, '@media (min-width: 48rem)': text.xl },
    lineHeight: { default: leading.lg, '@media (min-width: 48rem)': leading.xl },
    fontWeight: weight.display,
    letterSpacing: tokens['--xid-tracking-heading'],
    overflowWrap: 'anywhere',
  },
  subRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '0.25rem 1rem',
    fontSize: text.sm,
    color: tokens['--xid-muted-foreground'],
    minWidth: 0,
  },
  mono: {
    fontFamily: tokens['--xid-font-mono'],
    fontSize: text.xs,
    color: tokens['--xid-muted-foreground'],
    overflowWrap: 'anywhere',
  },
  idRow: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.25rem',
    minWidth: 0,
  },
  layout: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(0, 1fr)',
      '@media (min-width: 90rem)': '15rem minmax(0, 1fr)',
    },
    gap: { default: '1.5rem', '@media (min-width: 90rem)': '2.5rem' },
    alignItems: 'start',
  },
  attrs: {
    position: { default: 'static', '@media (min-width: 90rem)': 'sticky' },
    top: '4.5rem',
    paddingInlineEnd: { default: 0, '@media (min-width: 90rem)': '1.5rem' },
    borderInlineEndWidth: { default: 0, '@media (min-width: 90rem)': '1px' },
    borderInlineEndStyle: 'solid',
    borderInlineEndColor: tokens['--xid-border'],
    minHeight: { default: 'auto', '@media (min-width: 90rem)': '20rem' },
  },
  attrsSummary: {
    cursor: 'pointer',
    fontSize: text.base,
    fontWeight: weight.medium,
    paddingBlock: '0.25rem',
  },
  attrsTitle: {
    margin: 0,
    marginBottom: '1rem',
    fontSize: text.base,
    fontWeight: weight.medium,
  },
  attrsList: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(auto-fill, minmax(12rem, 1fr))',
      '@media (min-width: 90rem)': '1fr',
    },
    gap: '1rem 1.5rem',
    margin: 0,
    paddingTop: { default: '0.75rem', '@media (min-width: 90rem)': 0 },
  },
  attr: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.125rem',
    minWidth: 0,
  },
  attrLabel: {
    fontSize: text.xs,
    lineHeight: leading.xs,
    color: tokens['--xid-muted-foreground'],
  },
  attrValue: {
    margin: 0,
    fontSize: text.sm,
    lineHeight: leading.sm,
    overflowWrap: 'anywhere',
  },
  positive: {
    fontSize: text.xs,
    color: tokens['--xid-success'],
  },
  caution: {
    fontSize: text.xs,
    color: tokens['--xid-warning'],
  },
  content: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2rem',
    minWidth: 0,
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
    minWidth: 0,
  },
  sectionHead: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '0.75rem',
  },
  sectionText: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
    minWidth: 0,
    flex: '1 1 18rem',
  },
  sectionTitle: {
    margin: 0,
    fontSize: text.md,
    lineHeight: leading.md,
    fontWeight: weight.display,
    letterSpacing: tokens['--xid-tracking-title'],
  },
  sectionLead: {
    margin: 0,
    fontSize: text.sm,
    lineHeight: leading.body,
    color: tokens['--xid-muted-foreground'],
  },
  rows: {
    margin: 0,
    padding: 0,
    listStyle: 'none',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens['--xid-border'],
  },
  row: {
    display: 'grid',
    gridTemplateColumns: { default: '1fr', '@media (min-width: 48rem)': '11rem minmax(0, 1fr)' },
    gap: '0.25rem 1rem',
    paddingBlock: '0.75rem',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens['--xid-border'],
    fontSize: text.base,
  },
  rowLabel: {
    color: tokens['--xid-muted-foreground'],
  },
  rowValue: {
    margin: 0,
    minWidth: 0,
    overflowWrap: 'anywhere',
  },
  itemRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '0.5rem 1rem',
    paddingBlock: '0.875rem',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens['--xid-border'],
  },
  itemMain: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.125rem',
    minWidth: 0,
    flex: '1 1 16rem',
  },
  itemTitle: {
    fontSize: text.base,
    fontWeight: weight.medium,
    overflowWrap: 'anywhere',
  },
  itemSub: {
    fontSize: text.sm,
    lineHeight: leading.sm,
    color: tokens['--xid-muted-foreground'],
    overflowWrap: 'anywhere',
  },
  itemState: {
    fontSize: text.sm,
    color: tokens['--xid-muted-foreground'],
    minWidth: '4.5rem',
  },
  itemAction: {
    display: 'flex',
    justifyContent: 'flex-end',
    minWidth: '7rem',
  },
  muted: {
    color: tokens['--xid-muted-foreground'],
  },
  link: {
    color: tokens['--xid-accent'],
    textDecoration: 'none',
    fontSize: text.sm,
  },
  groupLabel: {
    margin: 0,
    paddingTop: '0.5rem',
    fontSize: text.sm,
    fontWeight: weight.medium,
    color: tokens['--xid-muted-foreground'],
  },
})
