import * as stylex from '@stylexjs/stylex'
import { tokens } from '@xid-kit/web-ui/styles/tokens.stylex'
import { leading, text, weight } from '@xid-kit/web-ui/styles/scale.stylex'

export const scope = stylex.create({
  trigger: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.625rem',
    width: '100%',
    minWidth: 0,
    paddingBlock: '0.375rem',
    paddingInline: '0.5rem',
    borderWidth: 0,
    borderRadius: tokens['--xid-radius'],
    backgroundColor: { default: 'transparent', ':hover': tokens['--xid-muted'] },
    color: tokens['--xid-fg'],
    fontFamily: tokens['--xid-font'],
    textAlign: 'start',
    cursor: { default: 'pointer', ':disabled': 'default' },
    outlineColor: tokens['--xid-accent'],
  },
  triggerCompact: {
    gap: '0.25rem',
    width: 'auto',
    paddingBlock: 0,
    paddingInline: 0,
    backgroundColor: 'transparent',
  },
  mark: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    width: '1.5rem',
    height: '1.5rem',
    borderRadius: tokens['--xid-radius-sm'],
    backgroundColor: tokens['--xid-fg'],
    color: tokens['--xid-surface'],
    fontSize: text.xs,
    fontWeight: 600,
  },
  triggerText: {
    display: 'flex',
    flexDirection: 'column',
    flexGrow: 1,
    minWidth: 0,
  },
  triggerName: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: text.base,
    lineHeight: leading.sm,
    fontWeight: weight.medium,
  },
  triggerNameCompact: {
    fontSize: text.xs,
    lineHeight: leading.xs,
    fontWeight: weight.regular,
    color: tokens['--xid-muted-foreground'],
  },
  triggerSub: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: text.xs,
    lineHeight: leading.xs,
    letterSpacing: tokens['--xid-tracking-small'],
    color: tokens['--xid-muted-foreground'],
  },
  chevron: {
    display: 'inline-flex',
    flexShrink: 0,
    color: tokens['--xid-muted-foreground'],
  },
  panel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
    width: 'min(19rem, calc(100vw - 3rem))',
    marginBlock: '-0.375rem',
    marginInline: '-0.5rem',
  },
  search: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    paddingBlock: '0.375rem',
    paddingInline: '0.5rem',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens['--xid-border'],
  },
  searchIcon: {
    display: 'inline-flex',
    color: tokens['--xid-muted-foreground'],
  },
  searchInput: {
    flexGrow: 1,
    minWidth: 0,
    borderWidth: 0,
    backgroundColor: 'transparent',
    color: tokens['--xid-fg'],
    fontFamily: tokens['--xid-font'],
    fontSize: 'max(16px, 0.875rem)',
    outline: 'none',
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1px',
    paddingTop: '0.25rem',
  },
  sectionLabel: {
    margin: 0,
    paddingBlock: '0.25rem',
    paddingInline: '0.5rem',
    fontSize: text.xs,
    lineHeight: leading.xs,
    fontWeight: weight.medium,
    color: tokens['--xid-faint-foreground'],
  },
  row: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.625rem',
    width: '100%',
    minHeight: { default: '2.75rem', '@media (pointer: fine)': '2.5rem' },
    paddingBlock: '0.25rem',
    paddingInline: '0.5rem',
    borderWidth: 0,
    borderRadius: tokens['--xid-radius'],
    backgroundColor: { default: 'transparent', ':hover': tokens['--xid-muted'] },
    color: tokens['--xid-fg'],
    fontFamily: tokens['--xid-font'],
    textAlign: 'start',
    textDecoration: 'none',
    cursor: 'pointer',
    outlineColor: tokens['--xid-accent'],
  },
  rowCurrent: {
    backgroundColor: tokens['--xid-muted'],
  },
  rowNested: {
    paddingInlineStart: '1.75rem',
  },
  rowMark: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    width: '1.5rem',
    height: '1.5rem',
    borderRadius: tokens['--xid-radius-sm'],
    backgroundColor: tokens['--xid-muted'],
    boxShadow: `inset 0 0 0 1px ${tokens['--xid-border']}`,
    color: tokens['--xid-muted-foreground'],
    fontSize: text.xs,
    fontWeight: 600,
  },
  rowMarkCurrent: {
    backgroundColor: tokens['--xid-fg'],
    boxShadow: 'none',
    color: tokens['--xid-surface'],
  },
  rowIcon: {
    display: 'inline-flex',
    justifyContent: 'center',
    flexShrink: 0,
    width: '1.5rem',
    color: tokens['--xid-muted-foreground'],
  },
  rowText: {
    display: 'flex',
    flexDirection: 'column',
    flexGrow: 1,
    minWidth: 0,
  },
  rowName: {
    fontSize: text.base,
    lineHeight: leading.sm,
    overflowWrap: 'anywhere',
  },
  rowSub: {
    fontSize: text.xs,
    lineHeight: leading.xs,
    color: tokens['--xid-muted-foreground'],
    overflowWrap: 'anywhere',
  },
  currentTag: {
    flexShrink: 0,
    fontSize: text.xs,
    color: tokens['--xid-accent'],
  },
  empty: {
    margin: 0,
    paddingBlock: '0.5rem',
    paddingInline: '0.5rem',
    fontSize: text.sm,
    color: tokens['--xid-muted-foreground'],
  },
  divided: {
    marginTop: '0.25rem',
    paddingTop: '0.25rem',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens['--xid-border'],
  },
})
