import * as stylex from '@stylexjs/stylex'
import { tokens } from '@xid-kit/web-ui/styles/tokens.stylex'
import { leading, text, weight } from '@xid-kit/web-ui/styles/scale.stylex'

export const topBar = stylex.create({
  bar: {
    position: 'sticky',
    top: 0,
    zIndex: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '1rem',
    minHeight: '3.5rem',
    paddingInlineStart: {
      default: '1rem',
      '@media (min-width: 48rem)': '0.75rem',
      '@media (min-width: 64rem)': '2.5rem',
    },
    paddingInlineEnd: { default: '0.75rem', '@media (min-width: 48rem)': '1.5rem' },
    backgroundColor: tokens['--xid-surface'],
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens['--xid-border'],
  },
  start: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    flexGrow: 1,
    minWidth: 0,
  },
  end: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.25rem',
    flexShrink: 0,
  },
  context: {
    display: { default: 'flex', '@media (min-width: 64rem)': 'none' },
    flexDirection: { default: 'column', '@media (min-width: 48rem)': 'row' },
    alignItems: { default: 'flex-start', '@media (min-width: 48rem)': 'center' },
    gap: { default: 0, '@media (min-width: 48rem)': '0.5rem' },
    minWidth: 0,
    flexGrow: { default: 1, '@media (min-width: 48rem)': 0 },
  },
  scopeRegular: {
    display: { default: 'none', '@media (min-width: 48rem)': 'block' },
    minWidth: 0,
    maxWidth: '16rem',
  },
  scopeNarrow: {
    display: { default: 'block', '@media (min-width: 48rem)': 'none' },
    minWidth: 0,
    maxWidth: '100%',
  },
  section: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    minWidth: 0,
    fontSize: { default: text.md, '@media (min-width: 48rem)': text.base },
    lineHeight: leading.base,
    fontWeight: { default: weight.medium, '@media (min-width: 48rem)': weight.regular },
    color: {
      default: tokens['--xid-fg'],
      '@media (min-width: 48rem)': tokens['--xid-muted-foreground'],
    },
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  sectionSlash: {
    display: { default: 'none', '@media (min-width: 48rem)': 'inline' },
    color: tokens['--xid-faint-foreground'],
  },
  menuButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    minHeight: { default: '2.25rem', '@media (pointer: coarse)': '2.75rem' },
    paddingInline: '0.75rem',
    borderRadius: tokens['--xid-radius'],
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens['--xid-border'],
    backgroundColor: { default: tokens['--xid-surface'], ':hover': tokens['--xid-muted'] },
    color: tokens['--xid-fg'],
    fontFamily: tokens['--xid-font'],
    fontSize: { default: text.md, '@media (min-width: 48rem)': text.base },
    fontWeight: weight.medium,
    cursor: 'pointer',
    flexShrink: 0,
  },
  menuButtonRegular: {
    display: {
      default: 'none',
      '@media (min-width: 48rem)': 'inline-flex',
      '@media (min-width: 64rem)': 'none',
    },
  },
  search: {
    display: { default: 'none', '@media (min-width: 48rem)': 'flex' },
    alignItems: 'center',
    gap: '0.5rem',
    width: { default: 'auto', '@media (min-width: 64rem)': '22.5rem' },
    marginInlineStart: {
      default: 0,
      '@media (min-width: 48rem)': 'auto',
      '@media (min-width: 64rem)': 0,
    },
    height: '2rem',
    paddingInlineStart: '0.625rem',
    paddingInlineEnd: '0.375rem',
    borderWidth: 0,
    borderRadius: tokens['--xid-radius'],
    boxShadow: `inset 0 0 0 1px ${tokens['--xid-border']}`,
    backgroundColor: tokens['--xid-sidebar'],
    color: tokens['--xid-muted-foreground'],
    fontFamily: tokens['--xid-font'],
    fontSize: text.sm,
    cursor: 'pointer',
    flexShrink: 0,
  },
  searchText: {
    flexGrow: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    textAlign: 'start',
    whiteSpace: 'nowrap',
  },
  searchLong: {
    display: { default: 'none', '@media (min-width: 64rem)': 'inline' },
  },
  searchShort: {
    display: { default: 'inline', '@media (min-width: 64rem)': 'none' },
  },
  kbd: {
    display: 'inline-flex',
    alignItems: 'center',
    height: '1.25rem',
    paddingInline: '0.3125rem',
    borderRadius: tokens['--xid-radius-sm'],
    boxShadow: `inset 0 0 0 1px ${tokens['--xid-border']}`,
    backgroundColor: tokens['--xid-surface'],
    fontFamily: tokens['--xid-font'],
    fontSize: text.xs,
    color: tokens['--xid-muted-foreground'],
    flexShrink: 0,
  },
  ghost: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.375rem',
    height: '2rem',
    paddingInline: '0.5rem',
    borderWidth: 0,
    borderRadius: tokens['--xid-radius'],
    backgroundColor: { default: 'transparent', ':hover': tokens['--xid-muted'] },
    color: tokens['--xid-muted-foreground'],
    fontFamily: tokens['--xid-font'],
    fontSize: text.sm,
    textDecoration: 'none',
    cursor: 'pointer',
  },
  ghostLabel: {
    whiteSpace: 'nowrap',
  },
  icon: {
    display: 'inline-flex',
  },
  iconButton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '2.75rem',
    height: '2.75rem',
    borderWidth: 0,
    borderRadius: tokens['--xid-radius'],
    backgroundColor: 'transparent',
    color: tokens['--xid-fg'],
    cursor: 'pointer',
  },
  avatarTrigger: {
    borderRadius: tokens['--xid-radius-full'],
  },
  identityTrigger: {
    justifyContent: 'flex-start',
    gap: '0.75rem',
    paddingBlock: '0.5rem',
    paddingInline: '0.5rem',
    borderRadius: tokens['--xid-radius'],
    textAlign: 'start',
  },
  avatar: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '1.75rem',
    height: '1.75rem',
    borderRadius: tokens['--xid-radius-full'],
    backgroundColor: tokens['--xid-muted'],
    boxShadow: `inset 0 0 0 1px ${tokens['--xid-border-strong']}`,
    color: tokens['--xid-fg'],
    fontSize: text.xs,
    fontWeight: weight.medium,
  },
  wideOnly: {
    display: { default: 'none', '@media (min-width: 64rem)': 'inline-flex' },
  },
  notNarrow: {
    display: { default: 'none', '@media (min-width: 48rem)': 'inline-flex' },
  },
  narrowOnly: {
    display: { default: 'inline-flex', '@media (min-width: 48rem)': 'none' },
  },
})
