import * as stylex from '@stylexjs/stylex'
import { tokens } from '@xid-kit/web-ui/styles/tokens.stylex'
import { text } from '@xid-kit/web-ui/styles/scale.stylex'

export const sections = stylex.create({
  layout: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(0, 1fr)',
      '@media (min-width: 64rem)': '10rem minmax(0, 40rem)',
    },
    gap: { default: '1.5rem', '@media (min-width: 64rem)': '2.5rem' },
    alignItems: 'start',
  },
  toc: {
    display: { default: 'none', '@media (min-width: 64rem)': 'flex' },
    flexDirection: 'column',
    gap: '1px',
    position: 'sticky',
    top: '4.5rem',
    margin: 0,
    padding: 0,
    listStyle: 'none',
  },
  tocLink: {
    display: 'block',
    paddingBlock: '0.375rem',
    paddingInline: '0.5rem',
    borderRadius: tokens['--xid-radius-sm'],
    color: { default: tokens['--xid-muted-foreground'], ':hover': tokens['--xid-fg'] },
    backgroundColor: { default: 'transparent', ':hover': tokens['--xid-muted'] },
    fontSize: text.sm,
    textDecoration: 'none',
  },
  stack: {
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    paddingBlock: '1.75rem',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens['--xid-border'],
    scrollMarginTop: '4.5rem',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  readonly: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
    fontSize: text.sm,
  },
  secretBox: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '0.75rem',
    padding: '0.875rem',
    borderRadius: tokens['--xid-radius'],
    boxShadow: `inset 0 0 0 1px ${tokens['--xid-border']}`,
  },
  uriRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    alignItems: 'end',
    gap: '0.5rem',
  },
  remove: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '2.25rem',
    height: '2.25rem',
    marginBottom: '0.0625rem',
    borderWidth: 0,
    borderRadius: tokens['--xid-radius'],
    backgroundColor: { default: 'transparent', ':hover': tokens['--xid-muted'] },
    color: tokens['--xid-muted-foreground'],
    cursor: 'pointer',
  },
  add: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.375rem',
    alignSelf: 'flex-start',
    padding: 0,
    borderWidth: 0,
    backgroundColor: 'transparent',
    color: tokens['--xid-accent'],
    fontFamily: tokens['--xid-font'],
    fontSize: text.sm,
    cursor: 'pointer',
  },
  actions: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '0.75rem',
  },
  blocked: {
    fontSize: text.sm,
    color: tokens['--xid-danger'],
  },
  danger: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '0.75rem',
    padding: '0.875rem',
    borderRadius: tokens['--xid-radius'],
    boxShadow: `inset 0 0 0 1px ${tokens['--xid-border']}`,
  },
})
