import { describe, expect, it } from 'vitest'
import { computeChainRows } from '../../queues/audit'
import {
  createAuditVerificationState,
  verifyAuditRows,
  type AuditChainVerificationState,
} from '../audit-verify'

const GENESIS_HASH = '0'.repeat(64)

function fields(id: string, occurredAt: string) {
  return {
    id,
    tenantId: 'tenant_1',
    orgId: 'org_1',
    eventType: 'user.updated',
    actorId: 'user_1',
    actorIp: '192.0.2.1',
    targetType: 'user',
    targetId: id,
    meta: { source: 'test' },
    occurredAt,
  }
}

async function validRows() {
  return computeChainRows(1, GENESIS_HASH, [
    fields('audit_1', '2026-07-28T00:00:00.000Z'),
    fields('audit_2', '2026-07-28T00:00:01.000Z'),
    fields('audit_3', '2026-07-28T00:00:02.000Z'),
  ])
}

function expectFailure(
  state: AuditChainVerificationState,
  reason: AuditChainVerificationState['failureReason'],
  seq: number,
): void {
  expect(state).toMatchObject({
    chainValid: false,
    brokenAtSeq: seq,
    failureReason: reason,
  })
}

describe('audit hash-chain verifier', () => {
  it('accepts a complete chain generated by the append path', async () => {
    const rows = await validRows()
    const state = createAuditVerificationState(1, GENESIS_HASH)

    await verifyAuditRows(state, rows)

    expect(state).toMatchObject({
      chainValid: true,
      nextSeq: 4,
      expectedPrevHash: rows[2]?.hash,
      recordCount: 3,
      brokenAtSeq: null,
      failureReason: null,
    })
  })

  it('rejects a non-zero genesis prev_hash', async () => {
    const rows = await validRows()
    const state = createAuditVerificationState(1, GENESIS_HASH)

    await verifyAuditRows(state, [{ ...rows[0]!, prevHash: 'f'.repeat(64) }])

    expectFailure(state, 'audit_genesis_missing', 1)
  })

  it('rejects the first missing sequence without accepting later rows', async () => {
    const rows = await validRows()
    const state = createAuditVerificationState(1, GENESIS_HASH)

    await verifyAuditRows(state, [rows[0]!, rows[2]!])

    expectFailure(state, 'audit_seq_gap', 2)
  })

  it('rejects a changed persisted hash', async () => {
    const rows = await validRows()
    const state = createAuditVerificationState(1, GENESIS_HASH)

    await verifyAuditRows(state, [{ ...rows[0]!, hash: 'f'.repeat(64) }])

    expectFailure(state, 'audit_chain_broken', 1)
  })

  it('verifies a partial range against the stored predecessor hash', async () => {
    const rows = await validRows()
    const state = createAuditVerificationState(2, rows[0]!.hash)

    await verifyAuditRows(state, rows.slice(1))

    expect(state).toMatchObject({
      chainValid: true,
      nextSeq: 4,
      recordCount: 2,
      failureReason: null,
    })
  })
})
